# Logging configuration file
version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - Line %(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "module": "%(module)s", "function": "%(funcName)s", "line": %(lineno)d, "message": "%(message)s"}'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  file_info:
    class: logging.FileHandler
    level: INFO
    formatter: detailed
    filename: logs/spr_analyzer.log
    mode: a
    encoding: utf-8
  
  file_error:
    class: logging.FileHandler
    level: ERROR
    formatter: detailed
    filename: logs/spr_analyzer_errors.log
    mode: a
    encoding: utf-8
  
  file_debug:
    class: logging.FileHandler
    level: DEBUG
    formatter: json
    filename: logs/spr_analyzer_debug.log
    mode: a
    encoding: utf-8

loggers:
  spr_analyzer:
    level: DEBUG
    handlers: [console, file_info, file_error, file_debug]
    propagate: false
  
  research_processor:
    level: DEBUG
    handlers: [console, file_info, file_error]
    propagate: false
  
  financial:
    level: DEBUG
    handlers: [console, file_info, file_error]
    propagate: false
  
  ml_models:
    level: INFO
    handlers: [console, file_info, file_error]
    propagate: false
  
  dashboard:
    level: INFO
    handlers: [console, file_info]
    propagate: false

root:
  level: WARNING
  handlers: [console, file_error]
